export const GET_FILTERS_BY_CATEGORY = 'GET_FILTERS_BY_CATEGORY';
export const GET_FILTERS_BY_CATEGORY_COMPLETE = 'GET_FILTERS_BY_CATEGORY_COMPLETE';

export const GET_FILTER_GROUPS_BY_CATEGORY = 'GET_FILTER_GROUPS_BY_CATEGORY';
export const GET_FILTER_GROUPS_BY_CATEGORY_COMPLETE = 'GET_FILTER_GROUPS_BY_CATEGORY_COMPLETE';

export const ADD_OR_UPDATE_FILTER_GROUP = 'ADD_OR_UPDATE_FILTER_GROUP';
export const DELETE_FILTER_GROUP = 'DELETE_FILTER_GROUP';
export const RELOCATE_FILTER = 'RELOCATE_FILTER';

export const GET_UNMAPPED_TRANSLATIONS_BY_CATEGORY = 'GET_UNMAPPED_TRANSLATIONS_BY_CATEGORY';
export const GET_UNMAPPED_TRANSLATIONS_BY_CATEGORY_COMPLETE = 'GET_UNMAPPED_TRANSLATIONS_BY_CATEGORY_COMPLETE';

export const GET_MAPPED_TRANSLATIONS_BY_CATEGORY = 'GET_MAPPED_TRANSLATIONS_BY_CATEGORY';
export const GET_MAPPED_TRANSLATIONS_BY_CATEGORY_COMPLETE = 'GET_MAPPED_TRANSLATIONS_BY_CATEGORY_COMPLETE';

export const ADD_OR_UPDATE_FILTER = 'ADD_OR_UPDATE_FILTER';

export const DELETE_FILTER = 'DELETE_FILTER';

export const GET_TRANSLATIONS_BY_ID = 'GET_TRANSLATIONS_BY_ID';
export const GET_TRANSLATIONS_BY_ID_COMPLETE = 'GET_TRANSLATIONS_BY_ID_COMPLETE';

export const ADD_OR_UPDATE_TRANSLATION = 'ADD_OR_UPDATE_TRANSLATION';
export const ADD_OR_UPDATE_TRANSLATION_BATCH = 'ADD_OR_UPDATE_TRANSLATION_BATCH';

export const DELETE_TRANSLATION_BY_ID = 'DELETE_TRANSLATION_BY_ID';

