FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["bikecompare.imaging.api/bikecompare.imaging.api.csproj", "bikecompare.imaging.api/"]

RUN dotnet restore "bikecompare.imaging.api/bikecompare.imaging.api.csproj"
COPY . .
WORKDIR "/src/bikecompare.imaging.api"
RUN dotnet build "bikecompare.imaging.api.csproj" -c Development -o /app

FROM build AS publish
RUN dotnet publish "bikecompare.imaging.api.csproj" -c Development -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
EXPOSE 8080
ENTRYPOINT ["dotnet", "bikecompare.imaging.api.dll"]