FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["bikecompare.listing.api/bikecompare.listing.api.csproj", "bikecompare.listing.api/"]

RUN dotnet restore "bikecompare.listing.api/bikecompare.listing.api.csproj"
COPY . .
WORKDIR "/src/bikecompare.listing.api"
RUN dotnet build "bikecompare.listing.api.csproj" -c Development -o /app

FROM build AS publish
RUN dotnet publish "bikecompare.listing.api.csproj" -c Development -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
EXPOSE 8080
ENTRYPOINT ["dotnet", "bikecompare.listing.api.dll"]